//! Relation handler trait and generic cascade/load helpers.
//!
//! This module provides the `RelationDescriptor` data structure and the
//! `RelationHandler` trait. Instead of generating inline query logic for
//! every entity, the proc-macro now only generates a list of descriptors.
//! The heavy lifting (cascading saves, loading relations, cascade deletes)
//! lives in the generic helper functions below, which are well-tested in
//! a single place.

use crate::{
    CorrosionOrmError, Executor,
    driver::from_row_db::FromRowDb,
    model::repository::Repo,
    query::{WhereClause, query_type::Value},
    schema::relation::RelationType,
    types::ColumnTrait,
};

/// Describes a single relation on an entity.
///
/// Generated by the `#[derive(Model)]` macro via `get_relations()`.
#[derive(Debug, Clone)]
pub struct RelationDescriptor {
    /// The kind of relation (HasOne, HasMany, BelongsTo, BelongsToMany).
    pub relation_type: RelationType,
    /// The Rust field name on the struct (for debugging / matching).
    pub field_name: &'static str,
    /// The foreign-key column name.
    pub foreign_key: &'static str,
    /// The target table name.
    pub target_table: &'static str,
    /// Whether this relation is eager-loaded by default.
    pub is_eager: bool,
}

/// Trait implemented by the proc-macro for every `Model` entity that has
/// relations. Provides a list of `RelationDescriptor`s so that the generic
/// helper functions in this module can operate without knowing the concrete
/// field types.
pub trait RelationHandler {
    /// Returns descriptors for all relations defined on this entity.
    fn get_relations() -> Vec<RelationDescriptor>;
}

// ---------------------------------------------------------------------------
// Generic cascade-save helpers
// ---------------------------------------------------------------------------

/// Cascade-save a **single** related entity (HasOne / BelongsTo).
///
/// Saves the related entity and returns the persisted version.
/// The caller is responsible for updating the parent struct field.
pub async fn cascade_save_single<Db, T>(related: &T, db: &mut Db) -> Result<T, CorrosionOrmError>
where
    Db: Executor,
    T: Repo<Db>,
{
    related.save(db).await
}

/// Cascade-save a **collection** of related entities (HasMany).
///
/// Each child is cloned, its foreign key is set to `parent_id` via the
/// `set_fk` closure, and then saved. Returns the persisted children.
pub async fn cascade_save_many<Db, Child, ParentId>(
    children: &[Child],
    parent_id: &ParentId,
    set_fk: impl Fn(&mut Child, &ParentId),
    db: &mut Db,
) -> Result<Vec<Child>, CorrosionOrmError>
where
    Db: Executor,
    Child: Repo<Db> + Clone,
{
    let mut results = Vec::with_capacity(children.len());
    for item in children {
        let mut child = (*item).clone();
        set_fk(&mut child, parent_id);
        results.push(child.save(db).await?);
    }
    Ok(results)
}

// ---------------------------------------------------------------------------
// Generic relation-loading helpers
// ---------------------------------------------------------------------------

/// Load a **single** related entity by its primary key (HasOne / BelongsTo).
pub async fn load_single<Db, T>(
    id: T::PrimaryKey,
    db: &mut Db,
) -> Result<Option<T>, CorrosionOrmError>
where
    Db: Executor,
    T: Repo<Db>,
{
    T::get_by_id(id, db).await
}

/// Load a **collection** of related entities by foreign key (HasMany).
///
/// Uses `find().filter(fk_column.eq(parent_id)).all()` and returns the results.
/// The caller is responsible for calling `load_relations` on each child if needed.
pub async fn load_many<Db, Child>(
    parent_id: Value,
    fk_column: Child::Column,
    db: &mut Db,
) -> Result<Vec<Child>, CorrosionOrmError>
where
    Db: Executor,
    Child: Repo<Db> + Send + Unpin + FromRowDb,
    Child::Column: ColumnTrait,
{
    Child::find()
        .filter(WhereClause::eq(fk_column, parent_id))
        .all(db)
        .await
}

// ---------------------------------------------------------------------------
// Generic cascade-delete helpers
// ---------------------------------------------------------------------------

/// Cascade-delete a **single** related entity (HasOne / BelongsTo).
pub async fn cascade_delete_single<Db, T>(related: T, db: &mut Db) -> Result<(), CorrosionOrmError>
where
    Db: Executor,
    T: Repo<Db>,
{
    related.delete(db).await
}

/// Cascade-delete a **collection** of related entities by foreign key (HasMany).
///
/// Finds all children matching the parent's primary key and deletes them
/// one by one.
pub async fn cascade_delete_many<Db, Child>(
    parent_id: Value,
    fk_column: Child::Column,
    db: &mut Db,
) -> Result<(), CorrosionOrmError>
where
    Db: Executor,
    Child: Repo<Db> + Send + Unpin + FromRowDb,
    Child::Column: ColumnTrait,
{
    let children = Child::find()
        .filter(WhereClause::eq(fk_column, parent_id))
        .all(db)
        .await?;
    for item in children {
        item.delete(db).await?;
    }
    Ok(())
}
